version: 2.1

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    environment:
      clientId: a
      clientSecret: a
      domain: a
      audience: a
    steps:
      - checkout
      - run: |
          # echo Hello, World!

workflows:
  test_and_build:
    jobs:
      - test
