version: 2.1

jobs:
  analyse:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: |
          export PATH="$PATH:/root/.dotnet/tools"
          apt-get update
          apt-get install curl
          apt-get install unzip
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:$SONAR_PRO_KEY /o:$SONAR_ORG_KEY /d:sonar.login=$SONAR_TOKEN /d:sonar.cs.opencover.reportsPaths=coverage.xml
          dotnet build --no-incremental
          coverlet dotnet/src/HonkService.Tests/bin/Debug/net6.0/HonkService.Tests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
          dotnet sonarscanner end /d:sonar.login=$SONAR_TOKEN
      - sonarcloud/scan
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: |
          cd dotnet/src/HonkService.Tests
          dotnet test HonkService.Tests.csproj
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run: |
          cd dotnet/src/HonkService.Api
          dotnet build -c Release

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  test_and_build:
    jobs:
      - analyse
      - test:
         requires:
           - analyse
      - build:
          requires:
            - test